# Plots a .tsv file. This was a simple script used to generate
# the graph of the MS-SSIM in the paper.

import matplotlib.pyplot as plt
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--input_file', type=str, default="Data/msssim.tsv",
                        help='the .tsv file that contains the msssim scores '
							 'generated by using msssim.py')

parser.add_argument('--output_file', type=str, default="Data/msssim",
                        help='The name of the output figure file that you '
							 'want to generate.')

args = parser.parse_args()

def open_tsv(file_name):
	with open(file_name, 'r') as f:
		tsv = f.readlines()

	ret = []
	for l in tsv:
		ret.append(l.split('\t'))

	print(ret)
	return ret

tsv = open_tsv(args.tsv_file)

x = []
y = []
for i in tsv:
	x.append(i[1])
	y.append(i[4])


plt.scatter(x, y)
plt.plot([0,1], [0,1])
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.xlabel('training data MS-SSIM value')
plt.ylabel('samples MS-SSIM value')

output_file_name = args.output_file + '.pdf'
plt.savefig(output_file_name, format='pdf')
